name: "CI"

on:
  push:
  pull_request:

jobs:
  test:
    name: "ğŸ§ª Test"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14]
    env:
      REACT_APP_API_USERNAME: ${{ secrets.API_USERNAME }}
      REACT_APP_API_PASSWORD: ${{ secrets.API_PASSWORD }}
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ§° Install Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: "ğŸ§° Install dependencies"
        run: yarn install
      - name: "ğŸ—ï¸ Build package"
        run: yarn build
      - name: "ğŸ§ª Run Cypress tests"
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn start
          wait-on: "http://localhost:3000"
      - name: "ğŸ“¤ Upload Cypress sceenshots"
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Cypress sceenshots
          path: cypress/screenshots
      - name: "ğŸ“¤ Upload Cypress videos"
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Cypress videos
          path: cypress/videos
      - name: "ğŸ“¤ Upload test coverage"
        uses: actions/upload-artifact@v2
        with:
          path: coverage/
          name: Test coverage
      - name: "ğŸ“¤ Publish test coverage"
        uses: codecov/codecov-action@v1
